name: CD Multistep
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: node-app
        steps:
            - uses: actions/checkout@v3

            - name: Print Current Working Directory
              run: pwd
            
            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: lint
        defaults:
            run:
                working-directory: node-app
        steps:
            - uses: actions/checkout@v3
            
            - name: Install dependencies
              run: npm ci

            - name: Test code
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        needs: test
        defaults:
            run:
                working-directory: node-app
        steps:
            - uses: actions/checkout@v3

            - name: Build code
              run: npm run build
            
            - name: Deploy
              run: echo "Deploying to production server..."