name: CD
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: node-app
        steps:
            - uses: actions/checkout@v3

            - name: Print Current Working Directory
              run: pwd

            - name: Setups node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            
            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint
            
            - name: Test code
              run: npm test

            - name: Build code
              run: npm run build