name: Issues Workflow
on: 
    issues:
        types: [opened, edited, milestoned, demilestoned, closed, reopened]
jobs:
    issue-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Print the Issue
              run: echo ${{ toJson(github.event.issue) }}

